# あなたのスプレッドシートのURLから抜き出したID
spreadsheet_id = "1A74_uOk3J6bl3vG6ORbVLfmiI15puGmxdvjU7HIVVow"
[gcp_service_account]
type = "service_account"
project_id = "claude-sheet-bot"
private_key_id = "e0a91aa937087ecbbfb1fe5fb9c85480c906ac37"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCzIrXw0rBPjUj7\n...（中略）...i0HI=\n-----END PRIVATE KEY-----\n"
client_email = "sheet-operator@claude-sheet-bot.iam.gserviceaccount.com"
client_id = "109487471469513104374"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheet-operator%40claude-sheet-bot.iam.gserviceaccount.com"
